### ISSUE TITLE
Some Questions about Time Measurement

### ISSUE THREAD

**Issue by qxzhou1010** [human-analysis/secure-face-matching#1]
Hello, recently I downloaded your github code and reproduced it on my own machine. First I used gendata.py to generate data, and then I used Enrolment-BFV-1-To-1. CPP to encrypt features. After observation, 16 64-dimensional features were encrypted here.  The Enrollment time (+ read & write) here is 1480.02, The Enrollment time here is 1313.08 millliseconds ， and the,  I continue to use authentication-bfv-1-to-1 to match probe with the previously encrypted feature data.  The verification time of single probe is 342.364 million seconds. so, I found that this time is somewhat different from your time in the paper. moreover, the feature dimension here is only 64 dimensions. may I ask what causes this?

**Comment by vboddeti** [comment]
I am not sure how you are measuring the time for me to give you an informed answer. If it is the time to run the whole script for one pair of features, it is not correct. During enrollment and authentication, a lot of time is spent on generating the keys, etc. which should be excluded from the matching time. 

Similarly, the time needed to load the data from the disk should be excluded. In my experiments, time is measured assuming the encrypted data is already in memory.

**Comment by qxzhou1010** [comment]
Ok, I have another question. In authentication, I will calculate a score. What is the meaning of this score?  Why are there negative numbers?  What does negative number mean?  Does score mean that the current probe matches the corresponding gallery to the highest degree?  Are the serial numbers of probe and gallery one to one?  For example, should the correct match for probe 1 be gallery 1?

**Comment by vboddeti** [comment]
The code is written to calculate inner products, so the value can potentially be between -infinity and + infinity. If you want to calculate Euclidean distance then, you will have to calculate three inner products. 

The demo uses toy data generated in python file. Please check how the toy data is being generated to figure out the correct match indices.
