### ISSUE TITLE
is the result accurately？

### ISSUE THREAD

**Issue by mapleshi** [human-analysis/secure-face-matching#2]
The encrypted face data recognition results are inaccurate,Because I use the face data in plain text, it can be correctly identified.
So, Have you verified the correctness and validity of the encryption and decryption method?

**Comment by vboddeti** [comment]
The encryption parameters have to be set appropriately in order for the decrypted results to be correct. These parameters depend on the dimensionality of the features, whether you are doing 1:1 or 1:N matching, etc. The default parameters in the repo are placeholders and need to be adjusted for your application.

Also, note that we are only computing inner products, which is equivalent to cosine similarity if the features are normalized. If the features are not normalized the results will be inaccurate.
