### ISSUE TITLE
1:1 Matching and 1:N Matching

### ISSUE THREAD

**Issue by thoongee** [human-analysis/secure-face-matching#4]
I'm curious about the difference between 1:1 Matching and 1:N Matching. I read and followed the Readme file. The result of 1-to-1 authentication is a matching score of gallery 0-15 for each probe. However, the result of 1-to-n authentication is the same as 1-to-1. It only takes longer for the results to be calculated. I'm not sure what the difference is between 1-to-1 and 1-to-n.

**Comment by vboddeti** [comment]
The 1:1 matching and 1:N matching use a different encoding scheme for the data. If your gallery size is small, 1:1 matching will be faster, but if your gallery size is large, 1:N matching will be faster. The cross-over point between the two can be estimated easily (see Table 2 and Figure 3 of [1]).

[1] HERS: Homomorphically Encrypted Representation Search, TBIOM 2022
